/*
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#pragma once

/** \file
 * \ingroup bke
 */

#include <mutex>

#include "FN_generic_virtual_array.hh"

#include "BLI_float3.hh"
#include "BLI_float4x4.hh"
#include "BLI_vector.hh"

#include "BKE_attribute_math.hh"

struct Curve;

class Spline;
using SplinePtr = std::unique_ptr<Spline>;

/**
 * A spline is an abstraction of a single branchless curve section, its evaluation methods,
 * and data. The spline data itself is just control points and a set of attributes.
 *
 * Any derived class of Spline has to manage two things:
 *  1. Evaluating the positions based on the stored control point data.
 *  2. Interpolating arbitrary attribute data from the control points to evaluated points.
 *
 * Beyond that, everything else is the bas class's responsibility, with minor exceptions. Futher
 * evaluation happens in a layer on top of the evaluated points generated by the derived types.
 * There are a few methods to evaluate a spline:
 *
 * Common evaluated data is stored in caches on the spline itself. That way operations on splines
 * don't need to worry about taking ownership of evaluated data when they don't need to.
 */
class Spline {
 public:
  enum Type {
    Bezier,
    NURBS,
    Poly,
  };

 private:
  Type type_;

 public:
  bool is_cyclic = false;

  enum NormalCalculationMode {
    ZUp,
    Minimum,
    Tangent,
  };
  NormalCalculationMode normal_mode;

 protected:
  mutable bool tangent_cache_dirty_ = true;
  mutable std::mutex tangent_cache_mutex_;
  mutable blender::Vector<blender::float3> evaluated_tangents_cache_;

  mutable bool normal_cache_dirty_ = true;
  mutable std::mutex normal_cache_mutex_;
  mutable blender::Vector<blender::float3> evaluated_normals_cache_;

  mutable bool length_cache_dirty_ = true;
  mutable std::mutex length_cache_mutex_;
  mutable blender::Vector<float> evaluated_lengths_cache_;

 public:
  virtual ~Spline() = default;
  Spline(const Type type) : type_(type){};
  Spline(Spline &other)
      : type_(other.type_), is_cyclic(other.is_cyclic), normal_mode(other.normal_mode)
  {
  }

  virtual SplinePtr copy() const = 0;

  Spline::Type type() const;

  virtual int size() const = 0;
  int segments_size() const;
  virtual int resolution() const = 0;
  virtual void set_resolution(const int value) = 0;

  virtual void drop_front(const int count) = 0;
  virtual void drop_back(const int count) = 0;

  virtual blender::MutableSpan<blender::float3> positions() = 0;
  virtual blender::Span<blender::float3> positions() const = 0;
  virtual blender::MutableSpan<float> radii() = 0;
  virtual blender::Span<float> radii() const = 0;
  virtual blender::MutableSpan<float> tilts() = 0;
  virtual blender::Span<float> tilts() const = 0;

  /**
   * Mark all caches for recomputation. This must be called after any operation that would
   * change the generated positions, tangents, normals, mapping, etc. of the evaluated points.
   */
  virtual void mark_cache_invalid() = 0;
  virtual int evaluated_points_size() const = 0;
  int evaluated_edges_size() const;

  float length() const;

  virtual blender::Span<blender::float3> evaluated_positions() const = 0;
  blender::Span<float> evaluated_lengths() const;
  blender::Span<blender::float3> evaluated_tangents() const;
  blender::Span<blender::float3> evaluated_normals() const;

  void bounds_min_max(blender::float3 &min, blender::float3 &max, const bool use_evaluated) const;

  struct LookupResult {
    /*
     * The index of the evaluated point before the result location.
     * In other words, the index of the edge that the result lies on.
     */
    int evaluated_index;
    /*
     * The index of the evaluated point after the result location,
     * accounting for wrapping when the spline is cyclic.
     */
    int next_evaluated_index;
    /**
     * The portion of the way from the evaluated point at #evaluated_index to the next point.
     */
    float factor;
  };
  LookupResult lookup_evaluated_factor(const float factor) const;
  LookupResult lookup_evaluated_length(const float length) const;

  virtual blender::fn::GVArrayPtr interpolate_to_evaluated_points(
      const blender::fn::GVArray &source_data) const = 0;

 protected:
  virtual void correct_end_tangents() const = 0;
};

/**
 * A Bézier spline is made up of a many curve segments, possibly achieving continuity of curvature
 * by constraining the alignment of curve handles. Evaluation stores the positions and a map of
 * factors and indices in a list of floats, which is then used to interpolate any other data.
 */
class BezierSpline final : public Spline {
 public:
  enum HandleType {
    Free,
    Auto,
    Vector,
    Align,
  };

 private:
  blender::Vector<HandleType> handle_types_start_;
  blender::Vector<blender::float3> handle_positions_start_;
  blender::Vector<blender::float3> positions_;
  blender::Vector<HandleType> handle_types_end_;
  blender::Vector<blender::float3> handle_positions_end_;
  blender::Vector<float> radii_;
  blender::Vector<float> tilts_;
  int resolution_;

  mutable bool offset_cache_dirty_ = true;
  mutable std::mutex offset_cache_mutex_;
  mutable blender::Vector<int> offset_cache_;

  mutable bool position_cache_dirty_ = true;
  mutable std::mutex position_cache_mutex_;
  mutable blender::Vector<blender::float3> evaluated_position_cache_;

  mutable bool mapping_cache_dirty_ = true;
  mutable std::mutex mapping_cache_mutex_;
  mutable blender::Vector<float> evaluated_mapping_cache_;

 public:
  virtual SplinePtr copy() const final;
  BezierSpline() : Spline(Type::Bezier){};
  BezierSpline(const BezierSpline &other)
      : Spline((Spline &)other),
        handle_types_start_(other.handle_types_start_),
        handle_positions_start_(other.handle_positions_start_),
        positions_(other.positions_),
        handle_types_end_(other.handle_types_end_),
        handle_positions_end_(other.handle_positions_end_),
        radii_(other.radii_),
        tilts_(other.tilts_),
        resolution_(other.resolution_)
  {
  }

  int size() const final;
  int resolution() const final;
  void set_resolution(const int value) final;

  void add_point(const blender::float3 position,
                 const HandleType handle_type_start,
                 const blender::float3 handle_position_start,
                 const HandleType handle_type_end,
                 const blender::float3 handle_position_end,
                 const float radius,
                 const float tilt);

  void drop_front(const int count) final;
  void drop_back(const int count) final;

  blender::MutableSpan<blender::float3> positions() final;
  blender::Span<blender::float3> positions() const final;
  blender::MutableSpan<float> radii() final;
  blender::Span<float> radii() const final;
  blender::MutableSpan<float> tilts() final;
  blender::Span<float> tilts() const final;

  blender::Span<HandleType> handle_types_start() const;
  blender::MutableSpan<HandleType> handle_types_start();
  blender::Span<blender::float3> handle_positions_start() const;
  blender::MutableSpan<blender::float3> handle_positions_start();
  blender::Span<HandleType> handle_types_end() const;
  blender::MutableSpan<HandleType> handle_types_end();
  blender::Span<blender::float3> handle_positions_end() const;
  blender::MutableSpan<blender::float3> handle_positions_end();

  bool point_is_sharp(const int index) const;
  bool handle_start_is_automatic(const int index) const;
  bool handle_end_is_automatic(const int index) const;

  void move_control_point(const int index, const blender::float3 new_position);

  void mark_cache_invalid() final;
  int evaluated_points_size() const final;

  blender::Span<int> control_point_offsets() const;
  blender::Span<float> evaluated_mappings() const;
  blender::Span<blender::float3> evaluated_positions() const final;
  struct InterpolationData {
    int control_point_index;
    int next_control_point_index;
    float factor;
  };
  InterpolationData interpolation_data_from_map(const float map) const;

  virtual blender::fn::GVArrayPtr interpolate_to_evaluated_points(
      const blender::fn::GVArray &source_data) const;

 private:
  void correct_end_tangents() const final;
  bool segment_is_vector(const int start_index) const;
  void evaluate_bezier_segment(const int index,
                               const int next_index,
                               blender::MutableSpan<blender::float3> positions) const;
  blender::Array<int> evaluated_point_offsets() const;
};

/**
 * Data for Non-Uniform Rational B-Splines. The mapping from control points to evaluated points is
 * influenced by a vector of knots, weights for each point, and the order of the spline. Every
 * mapping of data to evaluated points is handled the same way, but the posistions are cached in
 * the spline.
 */
class NURBSpline final : public Spline {
 public:
  enum KnotsMode {
    Normal,
    EndPoint,
    Bezier,
  };
  KnotsMode knots_mode;

  struct BasisCache {
    blender::Vector<float> weights;
    int start_index;
  };

 private:
  blender::Vector<blender::float3> positions_;
  blender::Vector<float> radii_;
  blender::Vector<float> tilts_;
  blender::Vector<float> weights_;
  int resolution_;
  uint8_t order_;

  mutable bool knots_dirty_ = true;
  mutable std::mutex knots_mutex_;
  mutable blender::Vector<float> knots_;

  mutable bool position_cache_dirty_ = true;
  mutable std::mutex position_cache_mutex_;
  mutable blender::Vector<blender::float3> evaluated_position_cache_;

  mutable bool basis_cache_dirty_ = true;
  mutable std::mutex basis_cache_mutex_;
  mutable blender::Vector<BasisCache> basis_cache_;

 public:
  SplinePtr copy() const final;
  NURBSpline() : Spline(Type::NURBS){};
  NURBSpline(const NURBSpline &other)
      : Spline((Spline &)other),
        positions_(other.positions_),
        radii_(other.radii_),
        tilts_(other.tilts_),
        weights_(other.weights_),
        resolution_(other.resolution_),
        order_(other.order_)
  {
  }

  int size() const final;
  int resolution() const final;
  void set_resolution(const int value) final;
  uint8_t order() const;
  void set_order(const uint8_t value);

  void add_point(const blender::float3 position,
                 const float radius,
                 const float tilt,
                 const float weight);

  void drop_front(const int count) final;
  void drop_back(const int count) final;

  bool check_valid_size_and_order() const;
  int knots_size() const;

  blender::MutableSpan<blender::float3> positions() final;
  blender::Span<blender::float3> positions() const final;
  blender::MutableSpan<float> radii() final;
  blender::Span<float> radii() const final;
  blender::MutableSpan<float> tilts() final;
  blender::Span<float> tilts() const final;

  blender::Span<float> knots() const;

  blender::MutableSpan<float> weights();
  blender::Span<float> weights() const;

  void mark_cache_invalid() final;
  int evaluated_points_size() const final;

  blender::Span<blender::float3> evaluated_positions() const final;

  blender::fn::GVArrayPtr interpolate_to_evaluated_points(
      const blender::fn::GVArray &source_data) const final;

 protected:
  void correct_end_tangents() const final;
  void calculate_knots() const;
  void calculate_basis_cache() const;
};

/**
 * A poly spline is like a bezier spline with a resolution of one. The main reason to distinguish
 * the two is for reduced complexity and increased performance, since interpolating data to control
 * points does not change it.
 */
class PolySpline final : public Spline {
 public:
  blender::Vector<blender::float3> positions_;
  blender::Vector<float> radii_;
  blender::Vector<float> tilts_;

 private:
 public:
  SplinePtr copy() const final;
  PolySpline() : Spline(Type::Bezier){};
  PolySpline(const PolySpline &other)
      : Spline((Spline &)other),
        positions_(other.positions_),
        radii_(other.radii_),
        tilts_(other.tilts_)
  {
  }

  int size() const final;
  int resolution() const final;
  void set_resolution(const int value) final;

  void add_point(const blender::float3 position, const float radius, const float tilt);

  void drop_front(const int count) final;
  void drop_back(const int count) final;

  blender::MutableSpan<blender::float3> positions() final;
  blender::Span<blender::float3> positions() const final;
  blender::MutableSpan<float> radii() final;
  blender::Span<float> radii() const final;
  blender::MutableSpan<float> tilts() final;
  blender::Span<float> tilts() const final;

  void mark_cache_invalid() final;
  int evaluated_points_size() const final;

  blender::Span<blender::float3> evaluated_positions() const final;

  blender::fn::GVArrayPtr interpolate_to_evaluated_points(
      const blender::fn::GVArray &source_data) const final;

 protected:
  void correct_end_tangents() const final;
};

/**
 * A #SplineGroup corresponds to the #Curve object data. The name is different for clarity, since
 * more of the data is stored in the splines, but also just to be different than the name in DNA.
 */
class SplineGroup {
 public:
  blender::Vector<SplinePtr> splines;

  SplineGroup *copy();

  void translate(const blender::float3 translation);
  void transform(const blender::float4x4 &matrix);
  void bounds_min_max(blender::float3 &min, blender::float3 &max, const bool use_evaluated) const;
};

SplineGroup *dcurve_from_dna_curve(const Curve &curve);